Badges
wildkain/TestGuru pull request #18
Opened 2018-05-21 18:20 UTC by wildkain

2018-05-22 19:28 UTC, iBublik requested changes

2018-05-22 19:28 UTC, iBublik commented on app/controllers/admin/badges_controller.rb
> +  @badge = Badge.new()
Что с отступами? И скобки тут не нужны вообще. Пора настроить rubocop и не коммитить уродливый код :)

2018-05-22 19:28 UTC, iBublik commented on app/controllers/admin/badges_controller.rb
> +      render :new
Эта вьюха упадет, т.к. ожидается наличие инстанс-переменно `@badge`

2018-05-22 19:28 UTC, iBublik commented on app/controllers/admin/badges_controller.rb
> +
Пустые методы лаконичнее так описывать - `def edit; end`

2018-05-22 19:28 UTC, iBublik commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :description, :image, :rule, :category_id, :level)
Не нужно под каждое правило отдельное поле заводить. Вполне достаточно одного обобщенного rule_parameter

2018-05-22 19:28 UTC, iBublik commented on app/controllers/test_passages_controller.rb
> +      service&.assign_badges
Зачем тут `&`? Ты же строкой выше создаешь объект сервиса, он никак не может быть nil-ом

2018-05-22 19:28 UTC, iBublik commented on app/models/badge.rb
> +  LEVELS  = { easy: "easy", medium: "medium", hard: "hard" }
Зачем это здесь?

2018-05-22 19:28 UTC, iBublik commented on app/models/badge.rb
> +  has_attached_file :image
Стоит как-то разделять ассоциации/валидации/кастомные команды - сейчас в кашу сливается

2018-05-22 19:28 UTC, iBublik commented on app/models/user.rb
> +    test_passages.select {|tp| tp.completed? }
`test_passages.select(&:completed?)`

2018-05-22 19:28 UTC, iBublik commented on app/services/badge_distributor_service.rb
> +    @category = @test_passage.test.categories.first
Непонятно зачем так много инстанс-переменных - большая часть нужна для одного конкретного правила. Не нужно засорять объект

2018-05-22 19:28 UTC, iBublik commented on app/services/badge_distributor_service.rb
> +    @badges_count = @user.badges.count.freeze
В чем идея? Числа - неизменяемые объекты, число 1 никогда не может стать числом 2 (это уже другой объект). Так что нет смысла замораживать числа

2018-05-22 19:28 UTC, iBublik commented on app/services/badge_distributor_service.rb
> +    if all_in_category?
Нужно идти от обратного - брать все бейджи, сохраненные в БД, на основе параметра rule вызывать проверку, если она выполняется - добавлять бейдж. 
Сделать это лучше как в курсе по Ruby с валидациями. Там мы не использовали ни case, ни if, т.к. это неудобно - при добавлении нового правила приходилось бы дописывать очередное условие.

2018-05-22 19:28 UTC, iBublik commented on db/migrate/20180520111608_add_description_and_rule_to_badges.rb
> +    add_column :badges, :description, :text
Не нужно плодить миграции. Таблица бейджей добавлена в рамках этой фичи, просто добавь в исходную миграцию недостающие поля

2018-05-22 19:28 UTC, iBublik commented on app/services/badge_distributor_service.rb
> +    user_tests_ids = @user.test_passages.pluck(:test_id)
У пользователя должна быть связь с тестами. Я заглянул в модель пользователя, там в принципе нерабочие ассоциации сейчас. Поправь, чтоб можно было тут упростить проверку - `@user.tests.where(id: @test_passage.test_id).count`

2018-05-22 19:28 UTC, iBublik commented on app/services/badge_distributor_service.rb
> +    check = all_tests & user_tests
Непонятное имя переменной

2018-05-22 19:28 UTC, iBublik commented on app/services/badge_distributor_service.rb
> +    check.eql?(all_tests)
Почему обычное сравнение не использовать? Плюс надо списки отсортировать, иначе у тебя проверка из-за пордка может вернуть false

2018-05-22 19:28 UTC, iBublik commented on app/services/badge_distributor_service.rb
> +    t_passages = @user.completed_tests.select do |tp|
Выборки лучше с помощью БД выполнять, а не на Ruby - `@user.completed_tests.joins(:test).where(tests: { level: ... })`. Запрос довольно длинный, так что стоит в скоуп вынести

2018-05-24 15:23 UTC, psylone approved these changes

2018-05-24 15:47 UTC, psylone approved these changes

2018-05-24 15:47 UTC, psylone commented on app/models/test_passage.rb
> +    end_time - Time.zone.now
Используй метод `Time.current`.

2018-05-24 16:45 UTC, merged